### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by jaasonw** [jaasonw/Database#1]
todo:
- [x] where stuff
    - [x] glue operators together
    - [x] rpn
    - [x] import stack
- [x] index structures
    - [x] make them print nicely
- [x] sql class
    - [x] writing files
    - [x] change select command to create a new table
- [x] make select check for file exist
    - [x] check in sql class
- [x] make insert update index
- [x] big 3 for sql
- [x] column map
- [x] make select > not ass
    - [x] make upper bound not trash
- [x] batch processing
    - [x] print command numbers
    - [x] print comments
    - [x] ignore comments/header guards
- [x] select where < thing is bigger than everything
    - [x] unscuff my upper and lower bounds pt 2
- [x] basically rework the entire string tokenizer tbh
    - [x] make a non scuffed combine quotes
    - [x] properly combine operators
    - [x] make words with numbers work
- [x] split index.h into 2 files
- [x] execute file command
- [ ] output to the file
    - [x] move invalid file error outside of table class
- [x] actual >= <= functions

wishlist:
- [ ] custom block size
- [ ] make execute string support multiple commands (split function)
- [ ] more sql commands cus why not
- [ ] sqlite commands
- [x] make the table list print nicer
- [ ] where parenthesis support
- [x] drop table command
- [ ] save temp tables
